### ISSUE TITLE
FIx Issue with `trim_radial` Function

### ISSUE THREAD

**Issue by Atomator** [mines-erds/core-ct#105]
`trim_radial` function not working

- [ ] fix `trim_radial`
- [ ] write tests for all axis

**Comment by TheSecondReal0** [comment]
Caused by using `axis` instead of `ax` on line 305 in core.py, this ends up always overwriting the function axis input to the z axis
![image](https://github.com/mines-erds/core-ct/assets/66881186/10f8f69e-1c27-433b-8414-58aab2b695ac)
