### ISSUE TITLE
Add Support for Scans in Arbitrary Orientations to DICOM Importer

### ISSUE THREAD

**Issue by TheSecondReal0** [mines-erds/core-ct#16]
## Description
Sometimes cores are scanned in such a way that each file contains a rectangular/vertical slice instead of a radial/horizontal slice. The `importers.dicom()` function should be able to account for this.

## Outcomes
- [ ] Add inputs to `importers.dicom()` that allow the user to specify if the core needs to be rotated
- [ ] Allow the user to specify if the core needs to be flipped vertically

**Comment by Atomator** [comment]
Closed this issue since it's functionality is covered by the `flip` and `rotate` functions
